version: 2
orbs:
  cypress: cypress-io/cypress@1

references:
  container_config: &container_config
    docker:
      - image: circleci/node:10



jobs:
  lint:
    <<: *container_config

    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-

      - run: npm install

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: lint
          command: npm run lint

  test_unit:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - restore_cache:
          keys:
            - node-v1-{{ checksum "package.json" }}
            - node-v1-

      - run: npm install

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: unit_test
          command: npm run test

  build:
    docker:
      # Specify the version you desire here
      - image: circleci/node:10
   
    environment:
      - NODE_ENV: production

    steps:
      - checkout

      - restore_cache:
          keys:
            # you can increment the "v1" prefix to invalidate all caches at once.
            - node-v1-{{ checksum "package.json" }}
            - node-v1-

      - run: npm install

      - save_cache:
          key: node-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: build the code
          command: npm run build

  

workflows:
  version: 2
  lint_and_deploy:
    jobs:
      - lint
      - test_unit
      - build
